# Generated by Django 4.2.3 on 2023-07-13 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account_user', '0002_vehicle_details'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle_details',
            name='vehicle_type',
            field=models.CharField(choices=[('2-wheeler', 'Two-wheeler'), ('3-wheeler', 'Three-wheeler'), ('4-wheeler', 'Four-wheeler')], default='2-wheeler', max_length=250),
        ),
    ]
